### PR TITLE
Extension documentation additions And Reformating from xhtml to html

### PR DESCRIPTION
**Pull request by se7enxweb**
Hello @peterkeung 

Here is the extension PR I talked about previously.
It's fairly clean and does a lot for the site in general.
It also includes the downloadable pdfs for the extensions.

Thank you for your continued support!

Cheers,
7x

### CODE REVIEW

**Comment by peterkeung** [comment]
Thanks for contributing!

Not worth fixing:
* Broken images in extension documentation

Needs fixing:
* The top link in the breadcrumb chain "ez publish" is broken

**Comment by se7enxweb** [comment]
@peterkeung 

Thank you for your prompt review.

I might be able to use the internet archive to find the missing image files if you could just highlight more specifically where they are missing, for me this is worth at least trying to get it right.

Thank you for catching the path problem and I will update the files accordingly very soon.

**Comment by se7enxweb** [comment]
OK... I found and fixed the missing images issue that i could see quickly.

I also payed special attention to the pathing for the ez publish nav item per section and so I think I have this one fixed as well.

Cheers,
7x

**Comment by se7enxweb** [comment]
@peterkeung Might I suggest you update the repository's GitHub description from the rather bland, "Copy of documentation files provided by ibexa" to "Official eZ Publish Legacy Documentation Maintained By Mugo (Provided By Ibexa)".

**Pull request merged**
